steps:
  - label: ':hammer: Build debian'
    commands:
      - make debian
    plugins:
      - docker-login#v2.0.1:
          username: farmwisesvc
          password-env: FARMWISE_SVC_PASSWORD
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: app
    artifact_paths:
      - "debian/*.deb"
